### ISSUE TITLE
dollarmath extension should be added  tomyst_enable_extensions with append() instead of add()?

### ISSUE THREAD

**Issue by eleurent** [Farama-Foundation/Celshast#4]
### What's happening?

The recent commit https://github.com/Farama-Foundation/Celshast/commit/bf3a5d1f1627b0e0b1fbe432f57b2ceac1269212 by @mgoulao broke docs build on HighwayEnv, see [example job](https://github.com/Farama-Foundation/HighwayEnv/actions/runs/6283998161/job/17064946997).

### Reproducer

Build docs on HighwayEnv.

### Expectation

Docs should build.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by mgoulao** [comment]
Thank you for reporting this issue., fixing it.
